schtasks /delete /f /tn "xinxiang_aps_etl_tool_down"
schtasks /delete /f /tn "xinxiang_aps_etl_qtime_spec"
schtasks /delete /f /tn "xinxiang_aps_etl_qtime_hold"
schtasks /delete /f /tn "xinxiang_aps_etl_wafer_start"
schtasks /delete /f /tn "xinxiang_aps_etl_vc_record"
schtasks /delete /f /tn "xinxiang_aps_etl_transport"
schtasks /delete /f /tn "xinxiang_aps_etl_etl_tool"
schtasks /delete /f /tn "xinxiang_aps_etl_size_control"
schtasks /delete /f /tn "xinxiang_aps_etl_season_rule"
schtasks /delete /f /tn "xinxiang_aps_etl_sampling_lot"
schtasks /delete /f /tn "xinxiang_aps_etl_ppid_info"
schtasks /delete /f /tn "xinxiang_aps_etl_hold_rls"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_tool_down"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_qtime_spec"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_qtime_hold"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_wafer_start"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_vc_record"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_transport"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_etl_tool"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_size_control"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_season_rule"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_sampling_lot"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_ppid_info"
schtasks /delete /f /tn "xinxiang_aps_etl_write_back_to_oracle_hold_rls"

pause