import os
import sys
import warnings

from xinxiang.jobs_manager.manager_jobs import delete_backup_files_by_day, delete_oracle_db_log_by_12_hours
from xinxiang.jobs_sync_his.sync_his_jobs import *
from xinxiang.jobs_sync_view import sync_view_jobs
from xinxiang.util import my_log, my_file

sys.path.insert(0, sys.path[0])
from xinxiang import main, config

if __name__ == '__main__':
    warnings.filterwarnings("ignore")
    my_file.init_folder()
    my_log.init_log(os.path.join(config.g_log_path, "NextChipETL.APS_ETL.log"))
    # 清除历史记录
    # delete_backup_files_by_day()
    # delete_oracle_db_log_by_12_hours()
    #
    # # His
    # sync_APS_TMP_LOTHISTORY()
    # sync_APS_MID_RSPILOT_RUN_HS()
    # sync_APS_MID_FHOPEHS()
    # sync_APS_TMP_MASK_HISTORY()
    # sync_APS_MID_FHOPEHS_RETICLE()
    # sync_APS_TMP_OCS_MAIN_H()
    # sync_APS_MID_OCS_JOB_GROUP_PO_STATE_H()
    # # # # View
    # sync_view_jobs.sync_APS_SYNC_APC_INHIBIT_BATCH()
    # sync_view_jobs.sync_APS_SYNC_EQP_STATUS_BOOKING_SETTING()
    # sync_view_jobs.sync_APS_SYNC_EQP_STATUS_CONVERT_AVAILABLE()
    # sync_view_jobs.sync_APS_SYNC_EQP_STATUS_E10_FORECAST()
    # sync_view_jobs.sync_APS_SYNC_EQP_STATUS_WAIT_TIME_SETTING()
    # sync_view_jobs.sync_APS_SYNC_MASK_INFO()
    # sync_view_jobs.sync_APS_SYNC_WIP()
    # sync_view_jobs.sync_APS_SYNC_FRDRBL_ID_DYB()
    # sync_view_jobs.sync_APS_SYNC_FUR_ED_CONTROL_SETTING()
    # sync_view_jobs.sync_APS_SYNC_MASK_MES_STATUS()
    # sync_view_jobs.sync_APS_SYNC_MOVE_TARGET_RANK()
    # sync_view_jobs.sync_APS_SYNC_PHOTO_PATH_CONVERT()
    # sync_view_jobs.sync_APS_SYNC_SCHE_GROUP_EQPG_SETTING()
    # sync_view_jobs.sync_APS_SYNC_SCHE_LOT_PURPTY_SETTING()
    # sync_view_jobs.sync_APS_SYNC_SCHE_LOT_TO_EQPG()
    # sync_view_jobs.sync_APS_SYNC_SCHE_OPE_NO_MODULE_SETTING()
    # sync_view_jobs.sync_APS_SYNC_SCHE_PM_PROP_TIME()
    # sync_view_jobs.sync_APS_SYNC_SCHE_UMT_MODULE_EQPG()
    # sync_view_jobs.sync_APS_SYNC_SETTING_MCS_LOCATION_MANUAL()
    # sync_view_jobs.sync_APS_SYNC_TRANSFER_TIME_DEFALUTE()
    # sync_view_jobs.sync_APS_SYNC_UMT_CONTROL_LOT()
    # sync_view_jobs.sync_APS_SYNC_UMT_EQP_CAP_STD()
    # sync_view_jobs.sync_APS_SYNC_UMT_PATH_CONVERT_SETTING()
    # sync_view_jobs.sync_APS_SYNC_UMT_RUN_RULE_BATCH_SIZE()
    # sync_view_jobs.sync_APS_SYNC_WET_ACID_CONTROL_SETTING()
    # sync_view_jobs.sync_APS_SYNC_WET_ACID_DATA()
    # sync_view_jobs.sync_APS_SYNC_WS_SCHEDULE_LOT_INFO()
    # sync_view_jobs.sync_APS_SYNC_DAILY_MOVE_TARGET()
    # sync_view_jobs.sync_APS_SYNC_RDS_RECIPEINFO()
    # sync_view_jobs.sync_APS_SYNC_CSLOT_FORCESAMP()
    # sync_view_jobs.sync_APS_SYNC_RETICLE_USE()
    # sync_view_jobs.sync_APS_SYNC_FLOW_DYB_RETURN()
    # sync_view_jobs.sync_APS_SYNC_FRLOT_EQP_RESOURCE_FLAG()
    # sync_view_jobs.sync_APS_SYNC_FVLOT_QTIME()
    # sync_view_jobs.sync_APS_SYNC_OCS_JOB_GROUP_SPEC()
    # sync_view_jobs.sync_APS_SYNC_RETICLE_PROD()
    # sync_view_jobs.sync_APS_SYNC_RSSPLIT_INFO()
    # sync_view_jobs.sync_APS_SYNC_RTD_QTIME_PROD_EQP()
    # sync_view_jobs.sync_APS_SYNC_UMT_RTD_BATCH_INFO()
    # sync_view_jobs.sync_APS_SYNC_FLOW()
    # sync_view_jobs.sync_APS_SYNC_QTIME_EQP_LOADING()
    # sync_view_jobs.sync_APS_SYNC_QTIME_EQP_LOADING_AM()
    # sync_view_jobs.sync_APS_SYNC_RTD_RECIPEGROUP()
    # sync_view_jobs.sync_APS_SYNC_CUT_LINE()
    # sync_view_jobs.sync_APS_SYNC_FLOW_ORDER_CHANGE()
    # sync_view_jobs.sync_APS_SYNC_LOT_LOCATION()
    # sync_view_jobs.sync_APS_SYNC_LOT_PURPOSE()
    # sync_view_jobs.sync_APS_SYNC_MCS_SCHED_TRANSFER_TIME()
    # sync_view_jobs.sync_APS_SYNC_MLIF_FOR_BATCH_MANU_REG()
    # sync_view_jobs.sync_APS_SYNC_PRODUCT_INFO()
    # sync_view_jobs.sync_APS_SYNC_RSPILOT_RUNING()
    # sync_view_jobs.sync_APS_SYNC_RTD_MOVE_TARGET()
    # sync_view_jobs.sync_APS_SYNC_RTD_WET_BATCH_SIZE_SETTING_NEW()
    # sync_view_jobs.sync_APS_SYNC_SELECT_LOT()
    # sync_view_jobs.sync_APS_SYNC_SHL_LOT_FIRE_NUMBER()
    # sync_view_jobs.sync_APS_SYNC_SHR_PRI()
    # sync_view_jobs.sync_APS_SYNC_UMT_BOAT_CONSTAINT_SETTING()
    # sync_view_jobs.sync_APS_SYNC_UMT_EQP_BATCH_SIZE_SETTING()
    # sync_view_jobs.sync_APS_SYNC_UO_HOLDLOT_WAIT_DISPATCH()
    # sync_view_jobs.sync_APS_SYNC_WET_ED_DATA()
    # sync_view_jobs.sync_APS_SYNC_WET_EXCHANGE_ACID_SETTING()
    # sync_view_jobs.sync_APS_SYNC_OP_CHAMBER_RULE()
    # sync_view_jobs.sync_APS_SYNC_PD_RECIPE_EQP_MAIN()
    # sync_view_jobs.sync_APS_SYNC_PF_PO_N1()
    # sync_view_jobs.sync_APS_SYNC_SCHE_APC_PA()
    # sync_view_jobs.sync_APS_SYNC_OCS_JOB_SPEC_GROUP_PO()
    # sync_view_jobs.sync_APS_SYNC_APC_SPLIT_WAFER()
    # sync_view_jobs.sync_APS_SYNC_CSCMBMRCPPRCFG_MFG()
    # sync_view_jobs.sync_APS_SYNC_CSCMBMRCPRULE()
    # sync_view_jobs.sync_APS_SYNC_HOLD_DETAIL_HISTORY()
    # sync_view_jobs.sync_APS_SYNC_LOT_PROCESS_MONITOR()
    # sync_view_jobs.sync_APS_SYNC_MASK_GROUP_MAPPLING()
    # sync_view_jobs.sync_APS_SYNC_PD_RECIPE_EQP_DYB()
    # sync_view_jobs.sync_APS_SYNC_QTIME_CONSTRAINT()
    # sync_view_jobs.sync_APS_SYNC_RMS_RECIPE_RETICLE()
    # sync_view_jobs.sync_APS_SYNC_SCHE_APC_LOT_SPECIAL_VALUE()
    # sync_view_jobs.sync_APS_SYNC_TMS_EQP_PARAMETER()
    # sync_view_jobs.sync_APS_SYNC_UMT_EQP_UNIT_PLAN_SETTING()
    # sync_view_jobs.sync_APS_SYNC_UMT_WET_RECIPE_TANK_RULE()
    # sync_view_jobs.sync_APS_SYNC_UNIT_EQP_CHAMBER_SETTING()
    # sync_view_jobs.sync_APS_SYNC_DIFF_BATCH_SIZE_MIX()
    # sync_view_jobs.sync_APS_SYNC_EQP_RCP_INHIBIT()
    #
    # sync_view_jobs.sync_APS_SYNC_FVEQP()
    # sync_view_jobs.sync_APS_SYNC_FVPORT()
    # sync_view_jobs.sync_APS_SYNC_IDLE_DUMMY_SPEC()
    # sync_view_jobs.sync_APS_SYNC_LOT_TO_EQP()
    # sync_view_jobs.sync_APS_SYNC_MCS_SCHED_LOCATION_INFO()
    # sync_view_jobs.sync_APS_SYNC_MLIF_FOR_WOT_MANU_REG()
    # sync_view_jobs.sync_APS_SYNC_MLIF_HOLD_LOT()
    # sync_view_jobs.sync_APS_SYNC_MM_FRSTK()
    # sync_view_jobs.sync_APS_SYNC_PRODUCT()
    # sync_view_jobs.sync_APS_SYNC_RTD_MFG_HWLD_SPEC()
    # sync_view_jobs.sync_APS_SYNC_RTD_RUN_LOTBYEQP_COUNT()
    # sync_view_jobs.sync_APS_SYNC_SGS_LOT_WIP()
    # sync_view_jobs.sync_APS_SYNC_SCHE_APC_PB()
    # sync_view_jobs.sync_APS_SYNC_WP_SPLIT_MERGE_DETAIL_HISTORY()
    # sync_view_jobs.sync_APS_SYNC_RTD_QTIME_FLOW()
    # sync_view_jobs.sync_APS_SYNC_RTD_LOT_RESOURCE_FLAG()
    # sync_view_jobs.sync_APS_SYNC_TRANSFER_TIME_DEFALUTE()
    # sync_view_jobs.sync_APS_SYNC_RSPILOT_RUN_HS()
    # sync_view_jobs.sync_APS_SYNC_ETL_TOOL()
    # sync_view_jobs.sync_APS_SYNC_RECIPE_NPW_RULEMAP()
    # sync_view_jobs.sync_APS_SYNC_FRLOT_FUTUREHOLD()
    # sync_view_jobs.sync_APS_SYNC_OCS_AUTODUMMY_COMPLETE()
    # sync_view_jobs.sync_APS_SYNC_RTD_WET_SPECIAL_LOT_CTRL_NEW()
    # sync_view_jobs.sync_APS_SYNC_CSDYNAMICMWF()
    # sync_view_jobs.sync_APS_SYNC_SAMPLING_RATE()
    # sync_view_jobs.sync_APS_SYNC_EQP_RECIPE_ED_ADD_VALUE()
    # sync_view_jobs.sync_APS_SYNC_OUT_DF_PURGE_COMBINE()
    # sync_view_jobs.sync_APS_SYNC_RTD_ID_OPE_CONFIG()
    # sync_view_jobs.sync_APS_SYNC_MLIF_EQP_SETTING()
    # sync_view_jobs.sync_APS_SYNC_UMT_BOTTLENECK_EQPG_SETTING()
    # sync_view_jobs.sync_APS_SYNC_EQP_ED_DATA_REPORT()
    # sync_view_jobs.sync_APS_SYNC_EQP_MODE_SETTING()
    # sync_view_jobs.sync_APS_SYNC_RTD_PREFER_TOOL()
    # sync_view_jobs.sync_APS_SYNC_FREQP_UTS()
    # sync_view_jobs.sync_APS_SYNC_MES_FRLOT_RETNLIST()
    # sync_view_jobs.sync_APS_SYNC_MAJOR_ANOMALY_EWS_LOT()
    # sync_view_jobs.sync_APS_SYNC_APC_INHIBIT_LOT()
    # sync_view_jobs.sync_APS_SYNC_NPW_RECIPE_GROUP()
    # sync_view_jobs.sync_APS_SYNC_RTD_IMP_SOURCE()
    # sync_view_jobs.sync_APS_SYNC_MES_FRLRCP()
    # sync_view_jobs.sync_APS_SYNC_STRIP_CHAMBER()
    # sync_view_jobs.sync_APS_SYNC_CSFLOWSAMPLINGCFG()
    # sync_view_jobs.sync_APS_SYNC_VIRT_QT_SETTING()
    # sync_view_jobs.sync_APS_SYNC_UMT_EQP_PM_DEFAULT_SETTING()
    # sync_view_jobs.sync_APS_SYNC_RTD_LIFE_TIME_CONTROL()
    #
    # sync_view_jobs.sync_APS_SYNC_FLOW_SUBFLOW_RETURN()
    # sync_view_jobs.sync_APS_SYNC_LOT_ANNOTATION_INFO_BRANCH()
    # sync_view_jobs.sync_APS_SYNC_FRQTIME_ACTION()
    # sync_view_jobs.sync_APS_SYNC_RECIPE_NPW_RULEMAP()
    #
    # sync_view_jobs.sync_APS_SYNC_ETL_TOOL()
    # sync_view_jobs.sync_APS_SYNC_UMT_EQP_WAIT_TIME_SETTING()
    # sync_view_jobs.sync_APS_SYNC_RTD_WET_SPECIAL_LOT_CONTROL()
    # sync_view_jobs.sync_APS_SYNC_UMT_EQP_QUEUE_SETTING()
    # sync_view_jobs.sync_APS_SYNC_RTD_CAPACITY_SETTING()
    # sync_view_jobs.sync_APS_SYNC_MES_BOND_PROD_PARTS()
    # sync_view_jobs.sync_APS_SYNC_FRLOT()
    # sync_view_jobs.sync_APS_SYNC_MES_FSBONDGRP_MAP()
    # sync_view_jobs.sync_APS_SYNC_NPW_PROCESSACTION()
    # sync_view_jobs.sync_APS_SYNC_CSMONWFRCFG()
    # sync_view_jobs.sync_APS_SYNC_CROSS_LOT_CSFRCROSSXFERLOTLIST()
    # sync_view_jobs.sync_APS_SYNC_PRODUCT_PLATFORM()
    # sync_view_jobs.sync_APS_SYNC_PRIORITY_DEFINE()
    # sync_view_jobs.sync_APS_SYNC_LOT_PRIORITY()
    # sync_view_jobs.sync_APS_SYNC_BONDING_OPE_NO()
    # sync_view_jobs.sync_APS_SYNC_QTIME_ISSUE_SETTING()
    # sync_view_jobs.sync_APS_SYNC_PRODUCT_PILOT()
    # sync_view_jobs.sync_APS_SYNC_EQP_DUMMY_BY_CHAMBER_RULE()
    # sync_view_jobs.sync_APS_SYNC_RTD_PIRUN_TASK()
    # sync_view_jobs.sync_APS_SYNC_PIRUN_TASK_SCHEDULE_LOT()
    # sync_view_jobs.sync_APS_SYNC_RTD_PIRUN_TASK_DEVICE()
    # sync_view_jobs.sync_APS_SYNC_RTD_PIRUN_TASK_INHIBIT_INFO()
    # sync_view_jobs.sync_APS_SYNC_EQP_PORT_NOCONCERN()
    # sync_view_jobs.sync_APS_SYNC_DIFF_FORMBATCH_TIME()
    # sync_view_jobs.sync_APS_SYNC_PRODUCT_NOPILOT()
    # sync_view_jobs.sync_APS_SYNC_UMT_PS_TUNNING_EQP_SETTING()
    # sync_view_jobs.sync_APS_SYNC_EQP_CHAMBER_EVENT_TRACKING()
    # sync_view_jobs.sync_APS_SYNC_UMT_SUB_FLOW_EQPG()
    # sync_view_jobs.sync_APS_SYNC_PROD_OPE_PREFER_TOOL()


