schtasks /create /tn xinxiang_aps_etl_wip /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_wip.vbs /sc minute /mo 15 /st 00:04 /f
schtasks /create /tn xinxiang_aps_etl_flow /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_flow.vbs /sc hourly /mo 1 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_tool_down /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_tool_down.vbs /sc minute /mo 15 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_qtime_spec /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_qtime_spec.vbs /sc hourly /mo 12 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_qtime_hold /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_qtime_hold.vbs /sc minute /mo 15 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_wafer_start /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_wafer_start.vbs /sc hourly /mo 1 /st 00:55 /f
schtasks /create /tn xinxiang_aps_etl_vc_record /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_vc_record.vbs /sc minute /mo 15 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_transport /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_transport.vbs /sc hourly /mo 12 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_etl_tool /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_etl_tool.vbs /sc minute /mo 15 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_size_control /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_size_control.vbs /sc minute /mo 15 /st 00:07 /f
schtasks /create /tn xinxiang_aps_etl_season_rule /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_season_rule.vbs /sc minute /mo 15 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_sampling_lot /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_sampling_lot.vbs /sc minute /mo 15 /st 00:09 /f
schtasks /create /tn xinxiang_aps_etl_ppid_info /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_ppid_info.vbs /sc hourly /mo 12 /st 13:00 /f
schtasks /create /tn xinxiang_aps_etl_hold_rls /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_hold_rls.vbs /sc minute /mo 15 /st 00:00 /f
schtasks /create /tn xinxiang_aps_etl_rls /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_rls.vbs /sc minute /mo 15 /st 00:04 /f
schtasks /create /tn xinxiang_aps_etl_pri_wip /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_pri_wip.vbs /sc minute /mo 15 /st 00:09 /f
schtasks /create /tn xinxiang_aps_etl_lothistory /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_lothistory.vbs /sc minute /mo 15 /st 00:09 /f
schtasks /create /tn xinxiang_aps_etl_lot_op_hist /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_lot_op_hist.vbs /sc hourly /mo 1 /st 00:55 /f
schtasks /create /tn xinxiang_aps_etl_mask_history /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_mask_history.vbs /sc minute /mo 15 /st 00:04 /f
schtasks /create /tn xinxiang_aps_etl_sgs_rls /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_sgs_rls.vbs /sc hourly /mo 1 /st 00:50 /f
schtasks /create /tn xinxiang_aps_etl_pirun /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_pirun.vbs /sc minute /mo 15 /st 00:08 /f
schtasks /create /tn xinxiang_aps_etl_sgs_rule /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_sgs_rule.vbs /sc hourly /mo 12 /st 01:00 /f
schtasks /create /tn xinxiang_aps_etl_mask_info /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_mask_info.vbs /sc minute /mo 15 /st 00:04 /f
schtasks /create /tn xinxiang_aps_etl_demand /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_demand.vbs /sc minute /mo 15 /st 00:09 /f
schtasks /create /tn xinxiang_aps_etl_special_cons /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_special_cons.vbs /sc minute /mo 15 /st 00:09 /f
schtasks /create /tn xinxiang_aps_etl_monitor /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_monitor.vbs /sc minute /mo 15 /st 00:09 /f
schtasks /create /tn xinxiang_aps_etl_merge_cons /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_merge_cons.vbs /sc minute /mo 15 /st 00:07 /f
schtasks /create /tn xinxiang_aps_etl_static_cons /tr D:\XinXiang\ETL_PYTHON\runner\run_aps_etl_static_cons.vbs /sc minute /mo 15 /st 00:08 /f